// <auto-generated />
using System;
using Library.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Library.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220809173955_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("Library.API.Models.Alugueis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAluguel")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDevolucao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataPrevisao")
                        .HasColumnType("TEXT");

                    b.Property<int>("LivroId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("LivroId");

                    b.ToTable("Alugueis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 2,
                            DataAluguel = new DateTime(2010, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataDevolucao = new DateTime(2010, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataPrevisao = new DateTime(2010, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LivroId = 2
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 2,
                            DataAluguel = new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataDevolucao = new DateTime(2010, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataPrevisao = new DateTime(2010, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LivroId = 1
                        },
                        new
                        {
                            Id = 3,
                            ClienteId = 2,
                            DataAluguel = new DateTime(2015, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataDevolucao = new DateTime(2010, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataPrevisao = new DateTime(2010, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LivroId = 4
                        },
                        new
                        {
                            Id = 4,
                            ClienteId = 2,
                            DataAluguel = new DateTime(2022, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataDevolucao = new DateTime(2010, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataPrevisao = new DateTime(2010, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LivroId = 3
                        });
                });

            modelBuilder.Entity("Library.API.Models.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeUsuario")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cidade = "Cascavel",
                            Email = "Artur@gmail.com",
                            Endereco = "Rua A",
                            NomeUsuario = "Artur"
                        },
                        new
                        {
                            Id = 2,
                            Cidade = "Caucaia",
                            Email = "Ana@gmail.com",
                            Endereco = "Rua T",
                            NomeUsuario = "Ana"
                        },
                        new
                        {
                            Id = 3,
                            Cidade = "São Paulo",
                            Email = "Vilma@gmail.com",
                            Endereco = "Rua K",
                            NomeUsuario = "Vilma"
                        },
                        new
                        {
                            Id = 4,
                            Cidade = "Fortaleza",
                            Email = "Vitor@gmail.com",
                            Endereco = "Rua E",
                            NomeUsuario = "Vitor"
                        });
                });

            modelBuilder.Entity("Library.API.Models.Editoras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeEditora")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Editoras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cidade = "Cascavel",
                            NomeEditora = "Artur"
                        },
                        new
                        {
                            Id = 2,
                            Cidade = "Caucaia",
                            NomeEditora = "Ana"
                        },
                        new
                        {
                            Id = 3,
                            Cidade = "São Paulo",
                            NomeEditora = "Vilma"
                        },
                        new
                        {
                            Id = 4,
                            Cidade = "Fortaleza",
                            NomeEditora = "Vitor"
                        });
                });

            modelBuilder.Entity("Library.API.Models.Livros", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Autor")
                        .HasColumnType("TEXT");

                    b.Property<int>("EditoraId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Lancamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeLivro")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EditoraId");

                    b.ToTable("Livros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Autor = "Navathe",
                            EditoraId = 2,
                            Lancamento = new DateTime(2010, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NomeLivro = "Banco de Dados"
                        },
                        new
                        {
                            Id = 2,
                            Autor = "Deitel",
                            EditoraId = 3,
                            Lancamento = new DateTime(2010, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NomeLivro = "Java Prático"
                        },
                        new
                        {
                            Id = 3,
                            Autor = "Deitel",
                            EditoraId = 3,
                            Lancamento = new DateTime(2010, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NomeLivro = "Php"
                        },
                        new
                        {
                            Id = 4,
                            Autor = "Cormen",
                            EditoraId = 3,
                            Lancamento = new DateTime(2010, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NomeLivro = "Vue JS"
                        });
                });

            modelBuilder.Entity("Library.API.Models.Alugueis", b =>
                {
                    b.HasOne("Library.API.Models.Clientes", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library.API.Models.Livros", "Livro")
                        .WithMany()
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Library.API.Models.Livros", b =>
                {
                    b.HasOne("Library.API.Models.Editoras", "Editora")
                        .WithMany()
                        .HasForeignKey("EditoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
