// <auto-generated />
using System;
using Library.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Library.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("Library.API.Models.Alugueis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientesId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAluguel")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDevolucao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataPrevisao")
                        .HasColumnType("TEXT");

                    b.Property<int>("LivroId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LivrosId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientesId");

                    b.HasIndex("LivrosId");

                    b.ToTable("Alugueis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 2,
                            DataAluguel = new DateTime(2010, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataDevolucao = new DateTime(2010, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataPrevisao = new DateTime(2010, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LivroId = 2
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 2,
                            DataAluguel = new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataDevolucao = new DateTime(2010, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataPrevisao = new DateTime(2010, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LivroId = 1
                        },
                        new
                        {
                            Id = 3,
                            ClienteId = 2,
                            DataAluguel = new DateTime(2015, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataDevolucao = new DateTime(2010, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataPrevisao = new DateTime(2010, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LivroId = 4
                        },
                        new
                        {
                            Id = 4,
                            ClienteId = 2,
                            DataAluguel = new DateTime(2022, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataDevolucao = new DateTime(2010, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataPrevisao = new DateTime(2010, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LivroId = 3
                        });
                });

            modelBuilder.Entity("Library.API.Models.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cidade = "Rua A",
                            Email = "Artur@gmail.com",
                            Endereco = "Cascavel",
                            Nome = "Artur"
                        },
                        new
                        {
                            Id = 2,
                            Cidade = "Rua T",
                            Email = "Ana@gmail.com",
                            Endereco = "Caucaia",
                            Nome = "Ana"
                        },
                        new
                        {
                            Id = 3,
                            Cidade = "Rua K",
                            Email = "Vilma@gmail.com",
                            Endereco = "São Paulo",
                            Nome = "Vilma"
                        },
                        new
                        {
                            Id = 4,
                            Cidade = "Rua E",
                            Email = "Vitor@gmail.com",
                            Endereco = "Fortaleza",
                            Nome = "Vitor"
                        });
                });

            modelBuilder.Entity("Library.API.Models.Editoras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeEditora")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Editoras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cidade = "Cascavel",
                            NomeEditora = "Artur"
                        },
                        new
                        {
                            Id = 2,
                            Cidade = "Caucaia",
                            NomeEditora = "Ana"
                        },
                        new
                        {
                            Id = 3,
                            Cidade = "São Paulo",
                            NomeEditora = "Vilma"
                        },
                        new
                        {
                            Id = 4,
                            Cidade = "Fortaleza",
                            NomeEditora = "Vitor"
                        });
                });

            modelBuilder.Entity("Library.API.Models.Livros", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Autor")
                        .HasColumnType("TEXT");

                    b.Property<int>("EditoraId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EditorasId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lancamento")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeLivro")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EditorasId");

                    b.ToTable("Livros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Autor = "Navathe",
                            EditoraId = 2,
                            Lancamento = 2002,
                            NomeLivro = "Banco de Dados"
                        },
                        new
                        {
                            Id = 2,
                            Autor = "Deitel",
                            EditoraId = 3,
                            Lancamento = 2005,
                            NomeLivro = "Java Prático"
                        },
                        new
                        {
                            Id = 3,
                            Autor = "Deitel",
                            EditoraId = 3,
                            Lancamento = 2010,
                            NomeLivro = "Php"
                        },
                        new
                        {
                            Id = 4,
                            Autor = "Cormen",
                            EditoraId = 3,
                            Lancamento = 2021,
                            NomeLivro = "Vue JS"
                        });
                });

            modelBuilder.Entity("Library.API.Models.Alugueis", b =>
                {
                    b.HasOne("Library.API.Models.Clientes", "Clientes")
                        .WithMany("Alugueis")
                        .HasForeignKey("ClientesId");

                    b.HasOne("Library.API.Models.Livros", "Livros")
                        .WithMany("Alugueis")
                        .HasForeignKey("LivrosId");
                });

            modelBuilder.Entity("Library.API.Models.Livros", b =>
                {
                    b.HasOne("Library.API.Models.Editoras", "Editoras")
                        .WithMany("Livros")
                        .HasForeignKey("EditorasId");
                });
#pragma warning restore 612, 618
        }
    }
}
